name = "personal-portfolio-next"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = ".vercel/output/static"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[site]
bucket = ".vercel/output/static"

[env.production]
workers_dev = true

[env.production.build]
command = "npm run build"
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
# 这里需要替换成你的自定义域名
NEXT_PUBLIC_SITE_URL = "https://carreypro.com"

[env.production.build.environment]
NODE_VERSION = "18"
