name = "personal-portfolio-next"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = "."
dist = ".next/static"

[site]
bucket = ".next/static"

[env.production]
name = "personal-portfolio-next"
node_version = "18"
workers_dev = true

[env.production.build]
command = "npm run pages:build"

[env.production.vars]
NEXT_PUBLIC_SITE_URL = "https://carreypro.com"
