name = "personal-portfolio-next"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = ".vercel/output/static"

[env.production]
node_version = "18"
workers_dev = true

[env.production.build]
command = "npm run build"

[env.production.vars]
NEXT_PUBLIC_SITE_URL = "https://carreypro.com"
